apiVersion: apps/v1
kind: Deployment
metadata:
  name: eric-aci
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: aksrepo01.azurecr.io/webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 80
